services:
  db:
    extends:
      file: ./pgdb/compose.yml
      service: db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oenobi
      - COMMERCE7_API_KEY=${COMMERCE7_API_KEY}
      - COMMERCE7_TENANT_ID=${COMMERCE7_TENANT_ID}
      - VINTRACE_API_KEY=${VINTRACE_API_KEY}
      - VINTRACE_BASE_URL=${VINTRACE_BASE_URL}
      - DASH_CACHE_KEY=${DASH_CACHE_KEY}
      - PYTHONDONTWRITEBYTECODE=1 # Optional: keeps your local folder clean of __pycache__
      - PYTHONUNBUFFERED=1 
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_DATABASE=oenobi
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules